data <- read.table("C:/Users/workshop/Desktop/exdata_data_household_power_consumption/household_power_consumption.txt" , sep = ";", header = TRUE)
data$Date <- as.Date(data$Date,"%d/%m/%Y")
data <- subset(data, Date >= as.Date("2007-02-01") & Date <= as.Date("2007-02-02"))
par(mfrow = c(2,2))
plot(as.POSIXct(paste(data$Date,data$Time)),as.numeric(as.character(data$Global_active_power)), type = "l", ylab = "Global Active Power (kilowatts)", xlab = "")
plot(as.POSIXct(paste(data$Date,data$Time)),as.numeric(as.character(data$Voltage)), type = "l", ylab = "Voltage", xlab = "datetime")
plot(as.POSIXct(paste(data$Date,data$Time)),as.numeric(as.character(data$Sub_metering_1)), type = "l", ylab = "Energy submeteting", xlab = "")
lines(as.POSIXct(paste(data$Date,data$Time)),as.numeric(as.character(data$Sub_metering_2)), type = "l", ylab = "Energy submeteting", xlab = "",col = "red")
lines(as.POSIXct(paste(data$Date,data$Time)),as.numeric(as.character(data$Sub_metering_3)), type = "l", ylab = "Energy submeteting", xlab = "", col = "blue")
legend( "topright" , legend=c("sub_metering_1", "sub_metering_2", "sub_metering_3") , col=c("black", "red", "blue"), lty = 1)
plot(as.POSIXct(paste(data$Date,data$Time)),as.numeric(as.character(data$Global_reactive_power)), type = "l", ylab = "Global_reactive_power",xlab = "")

dev.copy(png, file="plot4.png", width=480, height=480)
dev.off()