data <- read.table("C:/Users/workshop/Desktop/exdata_data_household_power_consumption/household_power_consumption.txt" , sep = ";", header = TRUE)
data$Date <- as.Date(data$Date,"%d/%m/%Y")
data <- subset(data, Date >= as.Date("2007-02-01") & Date <= as.Date("2007-02-02"))
plot(as.POSIXct(paste(data$Date,data$Time)),as.numeric(as.character(data$Sub_metering_1)), type = "l", ylab = "Energy submeteting", xlab = "")
lines(as.POSIXct(paste(data$Date,data$Time)),as.numeric(as.character(data$Sub_metering_2)), type = "l", ylab = "Energy submeteting", xlab = "",col = "red")
lines(as.POSIXct(paste(data$Date,data$Time)),as.numeric(as.character(data$Sub_metering_3)), type = "l", ylab = "Energy submeteting", xlab = "", col = "blue")
legend( "topright" , legend=c("sub_metering_1", "sub_metering_2", "sub_metering_3") , col=c("black", "red", "blue"), lty = 1)
dev.copy(png, file="plot3.png", width=480, height=480)
dev.off()